### ISSUE TITLE
Experiencing lag in Swamp Witch (Found a possible solution)

### ISSUE THREAD

**Issue by Ayylmao13pp** [Faboslav/villages-and-pillages#1]
Hello! I have decent PC specs (3080 TI and 5800x3d) and had severe fps issues in the swamp areas that have witches and villager 'prisoners'. I tried modifying certain things in the area and noticed that when I swapped all of the fence gates used as walkway rails to regular fences, I literally doubled my fps. Might be worth considering to help out those either with lower end PCs or those with heavy mod loads! :)

**Comment by Faboslav** [comment]
What was the issue or solution?

**Comment by Ayylmao13pp** [comment]
The issue was that I was using Panda's Extra Details mod ( https://modrinth.com/mod/pandas-extra-details ). Part of what it does it is add animations to fence gates opening and closing, and just the raw number of fence gates in the witch village dumpstered my FPS on a 3080 TI. By turning off the mod's functionality for the fence gate block it got my fps fixed. I guess even just having the fence gates idle with that mod is a performance hit.
