### ISSUE TITLE
Crash on NeoForge due to Forge version dependency

### ISSUE THREAD

**Issue by OKHI233** [Faboslav/villages-and-pillages#2]
### Minecraft version information

1.20.1

### Mod loader information

NeoForge

### Mod loader version information

47.1.87

### Mod version information

1.0.0

### Reproduction Steps

1. Put villagesandpillages-forge-mc1.20.1-1.0.0.jar into mods folder. 
2. Start the game. 

### Crash Report and latest.log

[crash-2024-01-16_02.42.15-fml.txt](https://github.com/Faboslav/villages-and-pillages/files/13942152/crash-2024-01-16_02.42.15-fml.txt)
[latest.log](https://github.com/Faboslav/villages-and-pillages/files/13942153/latest.log)

### Additional information

The mod requires a Forge version at least 47.2.0, but NeoForge for 1.20.1 never had a 47.2.0.

**Comment by Faboslav** [comment]
I think that sadly i cant resolve this until the yungs api also supports neoforge.

**Comment by OKHI233** [comment]
Wow, thanks for your fast reply. YUNG's API actually works on NeoForge, at least on 1.20.1.

**Comment by Faboslav** [comment]
Then i will need to do new release with some correction, will try to do it soon.

**Comment by drakray** [comment]
is it just a version dependency in the mods.toml that needs to be changed, or is there some code too?

**Comment by Faboslav** [comment]
Sorry everyone, i am just little bit busy with stuff and other projects, will try to do a proper release soon, since yungs api is finally updated too :).

**Comment by Faboslav** [comment]
NeoForge will be now supported with the 1.0.1 release available on CF, Modrinth and here on the GitHub, along with the 1.20.4/1.21.x versions.
